Consistently add whitespaces in // comments
etascale/argodsm pull request #127
Opened 2022-06-23 17:20 UTC by kostis

The rule that `cpplint` enforces is that // comments should be
preceeded by at least two spaces and followed by at least one.
Modify the code to follow it.

While at it, took the liberty to cleanup and/or remove some comments.

2022-06-24 08:23 UTC, lundgren87 requested changes
Left a few comments to address or dismiss.

2022-06-24 16:38 UTC, kostis commented on src/backend/mpi/swdsm.cpp
> +	size_of_all = argo_size;      // total distr. global memory
It can be, but in its context (surrounding code) it looks much better with more spaces.

2022-06-24 16:40 UTC, kostis commented on tests/allocators.cpp
> +			// std::cout << "collective_arr2 : " << j << " => "<< collective_arr2[j] << std::endl;
I am deleting them.

2022-06-27 11:37 UTC, lundgren87 approved these changes

2022-06-27 11:39 UTC, merged